# Trigger the workflow on push or pull request
on: [push, pull_request]

name: Build
jobs:
  build-and-export:
    name: Build, export and push to `sample-site-build` branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with the latest action rev
        uses: tsg-iitkgp/next-build-export-action@main
        env:
          BUILD_ONLY: true
          BUILD_DIR: sample-site
